spring.application.name=notification-service
server.port=4013
springdoc.api-docs.path=/notification-v3-api-docs
logging.level.root=info
spring.kafka.consumer.group-id=notification-service
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
