ALTER TABLE users ADD COLUMN status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE users ADD CONSTRAINT ck_users_status
    CHECK (status IN ('INVITED', 'ACTIVE', 'LOCKED', 'DISABLED'));
ALTER TABLE users ADD CONSTRAINT ck_users_role
    CHECK (role IN ('ADMIN', 'PATIENT', 'CLINICIAN', 'NURSE', 'REGISTRATION_STAFF',
                    'RECEPTIONIST', 'BILLING_STAFF', 'PHARMACIST', 'LAB_STAFF',
                    'PRIVACY_OFFICER', 'AUDITOR', 'ANALYST'));
