spring.application.name=audit-compliance-service
server.port=4015
springdoc.api-docs.path=/audit-compliance-v3-api-docs
logging.level.root=info
spring.kafka.consumer.group-id=audit-compliance-service
