spring.application.name=billing-service


server.port=4001
grpc.server.port=9001
grpc.server.security.enabled=true
grpc.server.security.certificateChain=classpath:certificates/server.crt
grpc.server.security.privateKey=classpath:certificates/server.key
