CREATE TABLE privacy_lock (id INTEGER PRIMARY KEY);
INSERT INTO privacy_lock VALUES (1);
CREATE TABLE privacy_grant (
 id UUID PRIMARY KEY, patient_id UUID NOT NULL, subject VARCHAR(200) NOT NULL,
 scope VARCHAR(40) NOT NULL CHECK (scope = 'FHIR_PATIENT_READ'),
 kind VARCHAR(20) NOT NULL CHECK (kind IN ('CONSENT','BREAK_GLASS')),
 expires_at TIMESTAMP WITH TIME ZONE NOT NULL, revoked BOOLEAN NOT NULL DEFAULT FALSE,
 created_by VARCHAR(200) NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL,
 evidence VARCHAR(200) NOT NULL, reviewed_by VARCHAR(200), review_evidence VARCHAR(200)
);
CREATE INDEX privacy_grant_lookup ON privacy_grant(patient_id, subject, scope, expires_at);
CREATE TABLE compliance_case (
 id UUID PRIMARY KEY, kind VARCHAR(30) NOT NULL CHECK (kind IN ('INCIDENT','ACCESS_REVIEW','RESTORE_DRILL','RETENTION_REVIEW','DOCUMENT_REVIEW')),
 status VARCHAR(30) NOT NULL, owner VARCHAR(200) NOT NULL, evidence VARCHAR(200) NOT NULL,
 due_at TIMESTAMP WITH TIME ZONE NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL,
 updated_at TIMESTAMP WITH TIME ZONE NOT NULL, legal_hold BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE TABLE compliance_history (
 id UUID PRIMARY KEY, case_id UUID NOT NULL REFERENCES compliance_case(id),
 actor VARCHAR(200) NOT NULL, action VARCHAR(40) NOT NULL, evidence VARCHAR(200) NOT NULL,
 occurred_at TIMESTAMP WITH TIME ZONE NOT NULL
);
