spring.application.name=analytics-service
server.port=4002
springdoc.api-docs.path=/analytics-v3-api-docs

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
